/**
 * @file mainwindow.h
 * @brief Main application window for the calculator Qt application.
 *
 * This file defines the MainWindow class, which handles the graphical user interface
 * of the calculator. It processes user interactions such as button clicks and keyboard
 * input, and connects them to the calculator logic.
 *
 * @author Patrik Kadlec
 */

#ifndef MAINWINDOW_H
#define MAINWINDOW_H

#include <QMainWindow>
#include <QPushButton>
#include <QKeyEvent>

QT_BEGIN_NAMESPACE
namespace Ui
{
	class MainWindow;
}
QT_END_NAMESPACE

/**
 * @class MainWindow
 * @brief Main window class handling UI interactions for the calculator.
 *
 * The MainWindow class manages user input (buttons and keyboard), updates the UI,
 * and triggers calculation logic. It acts as the central interface between the user
 * and the calculator backend.
 */
class MainWindow : public QMainWindow
{
	Q_OBJECT

	public:
		/**
		 * @brief Constructs the MainWindow object.
		 *
		 * @param parent Optional parent widget.
		 */
		explicit MainWindow(QWidget *parent = nullptr);

		/**
		 * @brief Destructor.
		 */
		~MainWindow() override;

	private slots:
		/**
		 * @brief Handles numeric button presses (0–9).
		 */
		void numberPressed();

		/**
		 * @brief Handles operator button presses (+, -, *, /, etc.).
		 */
		void operatorPressed();

		/**
		 * @brief Toggles the sign of the current number (+/-).
		 */
		void signPressed();

		/**
		 * @brief Executes the calculation of the current expression.
		 */
		void calculatePressed();

		/**
		 * @brief Deletes the last input character or clears part of the expression.
		 */
		void deletePressed();

		/**
		 * @brief Opens help or information dialog.
		 */
		void helpPressed();
	protected:
		/**
		 * @brief Handles keyboard input events.
		 *
		 * Overrides Qt keyPressEvent to allow keyboard-based calculator control.
		 *
		 * @param event The key event triggered by user input.
		 */
		void keyPressEvent(QKeyEvent *event) override;

	private:
		/// Pointer to the UI components generated by Qt Designer
		Ui::MainWindow *ui;
};

#endif // MAINWINDOW_H
